[package]
name = "send-mail"
version = "0.1.0"
authors = ["katsubushiken <katsubushiken@sinx.jp>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lettre = "0.10.0-alpha.3"